 

def GetPacketID(packet):
    if(len(packet) == 0):
        return 255
    if(packet[0] == ID_TIMESTAMP):
        if(len(packet)<9):
            return 255
        return packet[9]#sizeof(unsigned char) + sizeof(unsigned long)
    else:
        return packet[0]

#enum PacketEnumeration
ID_INTERNAL_PING = 6
ID_PING = 7
ID_PING_OPEN_CONNECTIONS = 8
ID_CONNECTED_PONG = 9
ID_REQUEST_STATIC_DATA = 10
ID_CONNECTION_REQUEST = 11
ID_AUTH_KEY = 12

ID_BROADCAST_PINGS = 14
ID_SECURED_CONNECTION_RESPONSE = 15
ID_SECURED_CONNECTION_CONFIRMATION = 16
ID_RPC_MAPPING = 17

ID_SET_RANDOM_NUMBER_SEED = 19
ID_RPC = 20
ID_RPC_REPLY = 21
ID_DETECT_LOST_CONNECTIONS = 23
ID_OPEN_CONNECTION_REQUEST = 24
ID_OPEN_CONNECTION_REPLY = 25
ID_OPEN_CONNECTION_COOKIE = 26

ID_RSA_PUBLIC_KEY_MISMATCH = 28
ID_CONNECTION_ATTEMPT_FAILED = 29

ID_NEW_INCOMING_CONNECTION = 30
ID_NO_FREE_INCOMING_CONNECTIONS = 31
ID_DISCONNECTION_NOTIFICATION = 32
ID_CONNECTION_LOST = 33
ID_CONNECTION_REQUEST_ACCEPTED = 34

ID_CONNECTION_BANNED = 36
ID_INVALID_PASSWORD = 37
ID_MODIFIED_PACKET = 38
ID_PONG = 39
ID_TIMESTAMP = 40
ID_RECEIVED_STATIC_DATA = 41
ID_REMOTE_DISCONNECTION_NOTIFICATION = 42
ID_REMOTE_CONNECTION_LOST = 43
ID_REMOTE_NEW_INCOMING_CONNECTION = 44
ID_REMOTE_EXISTING_CONNECTION = 45
ID_REMOTE_STATIC_DATA = 46

ID_ADVERTISE_SYSTEM = 55

ID_PLAYER_SYNC = 207
ID_MARKERS_SYNC = 208
ID_UNOCCUPIED_SYNC = 209
ID_TRAILER_SYNC = 210
ID_PASSENGER_SYNC = 211
ID_SPECTATOR_SYNC = 212
ID_AIM_SYNC = 203
ID_VEHICLE_SYNC = 200
ID_RCON_COMMAND = 201
ID_RCON_RESPONCE = 202
ID_WEAPONS_UPDATE = 204
ID_STATS_UPDATE = 205
ID_BULLET_SYNC = 206


IDS = {
"6" : "ID_INTERNAL_PING",
"7" : "ID_PING",
"8" : "ID_PING_OPEN_CONNECTIONS",
"9" : "ID_CONNECTED_PONG",
"10" : "ID_REQUEST_STATIC_DATA",
"11" : "ID_CONNECTION_REQUEST",
"12" : "ID_AUTH_KEY",
"14" : "ID_BROADCAST_PINGS",
"15" : "ID_SECURED_CONNECTION_RESPONSE",
"16" : "ID_SECURED_CONNECTION_CONFIRMATION",
"17" : "ID_RPC_MAPPING",
"19" : "ID_SET_RANDOM_NUMBER_SEED",
"20" : "ID_RPC",
"21" : "ID_RPC_REPLY",
"23" : "ID_DETECT_LOST_CONNECTIONS",
"24" : "ID_OPEN_CONNECTION_REQUEST",
"25" : "ID_OPEN_CONNECTION_REPLY",
"26" : "ID_OPEN_CONNECTION_COOKIE",
"28" : "ID_RSA_PUBLIC_KEY_MISMATCH",
"29" : "ID_CONNECTION_ATTEMPT_FAILED",
"30" : "ID_NEW_INCOMING_CONNECTION",
"31" : "ID_NO_FREE_INCOMING_CONNECTIONS",
"32" : "ID_DISCONNECTION_NOTIFICATION",
"33" : "ID_CONNECTION_LOST",
"34" : "ID_CONNECTION_REQUEST_ACCEPTED",
"36" : "ID_CONNECTION_BANNED",
"37" : "ID_INVALID_PASSWORD",
"38" : "ID_MODIFIED_PACKET",
"39" : "ID_PONG",
"40" : "ID_TIMESTAMP",
"41" : "ID_RECEIVED_STATIC_DATA",
"42" : "ID_REMOTE_DISCONNECTION_NOTIFICATION",
"43" : "ID_REMOTE_CONNECTION_LOST",
"44" : "ID_REMOTE_NEW_INCOMING_CONNECTION",
"45" : "ID_REMOTE_EXISTING_CONNECTION",
"46" : "ID_REMOTE_STATIC_DATA",
"55" : "ID_ADVERTISE_SYSTEM",
"200" : "ID_VEHICLE_SYNC",
"201" : "ID_RCON_COMMAND",
"202" : "ID_RCON_RESPONCE",
"203" : "ID_AIM_SYNC",
"204" : "ID_WEAPONS_UPDATE",
"205" : "ID_STATS_UPDATE",
"206" : "ID_BULLET_SYNC",
"207" : "ID_PLAYER_SYNC",
"208" : "ID_MARKERS_SYNC",
"209" : "ID_UNOCCUPIED_SYNC",
"210" : "ID_TRAILER_SYNC",
"211" : "ID_PASSENGER_SYNC",
"212" : "ID_SPECTATOR_SYNC"
}
